### ISSUE TITLE
The tool no matter what I crop, always only crops the upper left side of the image

### ISSUE THREAD

**Issue by edoantonioco** [brunon80/expo-image-crop#15]
This on newer code than 0.2.10, I got the code from master branch, just after it was upgraded to expo 35.
Edit: version 0.2.11

This on huawei p30 (I suspect it might happen in newer models of cameras since it used to work fine in my older phone)

So no matter what section of the image I decide to crop, it always only show me the upper left section of the image

This image explain it

![cropBug](https://user-images.githubusercontent.com/5560824/66583991-89465400-eb41-11e9-9444-0c49f4cccc02.jpeg)

**Comment by brunon80** [comment]
I tested on a physical phone, Lg K10 with Android 6 and various emulator models with Android 9 and could not reproduce this behavior, it is possible that ImageManipulator is returning wrong parameters on these devices, but I have no way to test since I can not reproduce this problem with the options I have.

**Comment by DrunkOldDog** [comment]
Same issue here with a physical HTC M9 with Android 7. It could be really helpful if on the prop "onPictureChoosed" it could return the width and height, to avoid the issue https://github.com/facebook/react-native/issues/22145

**Comment by brunon80** [comment]
resolved on expo-image-crop@0.2.15

**Comment by edoantonioco** [comment]
I can still reproduce this bug in latest version

**Comment by brunon80** [comment]
can you send me the picture you are testing?

**Comment by edoantonioco** [comment]
This bug in expo cli I did cleaned the cache but it still showed up.
I got an apk with latest version and it works there. Thanks for the fix.
